version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
         MYSQL_DATABASE: tpachato
         MYSQL_ROOT_PASSWORD:  
    volumes:
      - /home/mysql/data:/var/lib/mysql
  spring_app:
    image: mayakammoun/app:latest
    container_name: achatproject
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    