version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
   
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - /home/mysql/data:/var/lib/mysql
  spring_app:
    image: mayakammoun/app:latest
    container_name: achatproject
    
    ports:
      - 8089:8089
    depends_on:
      - mysqldb