pipeline {
  agent any
  stages {
    stage('Git Code'){
            steps{
                git branch: 'yasminebranche',
                url: 'https://github.com/mayakammoun/ProjetDevops/tpAchatProject.git'
            }
         }
        }
    }
